# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkaEtxWsw7oJmg02BVkl4ydrfqIW67_
"""

#include <stdio.h>
#include <unistd.h>

int main() {
    int process_count = 1;

    if (fork() == 0) {
        if (getpid() % 2 != 0) fork();
    } else {
        process_count++;
    }

    if (fork() == 0) {
        if (getpid() % 2 != 0) fork();
    } else {
        process_count++;
    }

    if (fork() == 0) {
        if (getpid() % 2 != 0) fork();
    } else {
        process_count++;
    }

    printf("Total processes created: %d\n", process_count);
    return 0;
}