# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkaEtxWsw7oJmg02BVkl4ydrfqIW67_
"""

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>

void sort(int arr[], int n) {
    for (int i = 0; i < n-1; i++)
        for (int j = i+1; j < n; j++)
            if (arr[i] < arr[j]) {
                int temp = arr[i];
                arr[i] = arr[j];
                arr[j] = temp;
            }
}

void printOddEven(int arr[], int n) {
    for (int i = 0; i < n; i++) {
        if (arr[i] % 2 == 0)
            printf("%d is even\n", arr[i]);
        else
            printf("%d is odd\n", arr[i]);
    }
}

int main(int argc, char *argv[]) {
    int arr[argc-1];
    for (int i = 1; i < argc; i++)
        arr[i-1] = atoi(argv[i]);

    int n = argc - 1;
    pid_t pid = fork();

    if (pid == 0) {
        sort(arr, n);
        exit(0);
    } else {
        wait(NULL);
        printOddEven(arr, n);
    }

    return 0;
}