# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkaEtxWsw7oJmg02BVkl4ydrfqIW67_
"""

#include <stdio.h>
#include <pthread.h>

void *run_thread(void *arg) {
    int id = *(int *)arg;
    printf("thread-%d running\n", id);
    printf("thread-%d closed\n", id);
    return NULL;
}

int main() {
    pthread_t threads[5];
    int ids[5];

    for (int i = 0; i < 5; i++) {
        ids[i] = i + 1;
        pthread_create(&threads[i], NULL, run_thread, &ids[i]);
        pthread_join(threads[i], NULL);
    }

    return 0;
}