# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkaEtxWsw7oJmg02BVkl4ydrfqIW67_
"""

#include <stdio.h>
#include <unistd.h>

int main() {
    printf("Parent process ID: %d\n", getpid());

    pid_t child_pid = fork();
    if (child_pid == 0) {
        printf("Child process ID: %d\n", getpid());

        for (int i = 0; i < 3; i++) {
            if (fork() == 0) {
                printf("Grandchild process ID: %d\n", getpid());
                exit(0);
            }
        }
    } else {
        wait(NULL);
    }

    return 0;
}