# -*- coding: utf-8 -*-
"""task1syscall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkaEtxWsw7oJmg02BVkl4ydrfqIW67_
"""

#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>

int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Usage: %s <filename>\n", argv[0]);
        return 1;
    }

    int fd = open(argv[1], O_WRONLY | O_CREAT, 0644);
    if (fd < 0) {
        perror("File open error");
        return 1;
    }

    char input[100];
    while (1) {
        printf("Enter a string (or -1 to stop): ");
        fgets(input, sizeof(input), stdin);
        if (strcmp(input, "-1\n") == 0)
            break;
        write(fd, input, strlen(input));
    }

    close(fd);
    return 0;
}