# -*- coding: utf-8 -*-
"""task2thread-num-print.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkaEtxWsw7oJmg02BVkl4ydrfqIW67_
"""

#include <stdio.h>
#include <pthread.h>

void *print_numbers(void *arg) {
    int thread_num = *(int *)arg;
    for (int i = 1; i <= 5; i++) {
        printf("Thread %d prints %d\n", thread_num, thread_num * 5 - 5 + i);
    }
    return NULL;
}

int main() {
    pthread_t threads[5];
    int ids[5];

    for (int i = 0; i < 5; i++) {
        ids[i] = i;
        pthread_create(&threads[i], NULL, print_numbers, &ids[i]);
        pthread_join(threads[i], NULL);
    }

    return 0;
}